apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: coding-platform
data:
  KUBERNETES_NAMESPACE: "coding-platform"
  EXECUTION_IMAGE: "rraup12/code-execution:latest"
  CORS_ORIGINS: "http://localhost:3000,https://cool-coding-platform.vercel.app"
  FASTAPI_ENV: "production"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: coding-platform
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres.dbwplldqbkoahbghmmme:R1ckster10%21%40bb@aws-1-us-east-2.pooler.supabase.com:6543/postgres"