apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: coding-platform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-manager
  namespace: coding-platform
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/exec"]
    verbs: ["get", "list", "create", "delete", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "create", "delete"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-pod-manager
  namespace: coding-platform
subjects:
  - kind: ServiceAccount
    name: backend-sa
    namespace: coding-platform
roleRef:
  kind: Role
  name: pod-manager
  apiGroup: rbac.authorization.k8s.io