---
# Horizontal Pod Autoscaler for Backend
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: coding-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 2  # Start with 2 replicas for redundancy
  maxReplicas: 10  # Scale up to 10 pods under heavy load
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0  # Scale up immediately when needed
      policies:
      - type: Percent
        value: 100  # Double the pods
        periodSeconds: 15  # Every 15 seconds
      - type: Pods
        value: 2  # Or add 2 pods
        periodSeconds: 15
      selectPolicy: Max  # Use the policy that scales faster
    scaleDown:
      stabilizationWindowSeconds: 300  # Wait 5 minutes before scaling down
      policies:
      - type: Percent
        value: 50  # Remove 50% of pods
        periodSeconds: 60  # Every minute
      - type: Pods
        value: 1  # Or remove 1 pod
        periodSeconds: 60
      selectPolicy: Min  # Use the policy that scales slower
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70  # Scale when CPU hits 70%
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80  # Scale when memory hits 80%