app = "cool-coding-platform"
primary_region = "ord"

[build]
  dockerfile = "backend/Dockerfile.production"

[http_service]
  internal_port = 8002
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = "requests"
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[env]
  PORT = "8002"
  ENVIRONMENT = "production"