version: '3.8'

services:
  test-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: test_coolcoding
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5433:5432"
    volumes:
      - test_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d test_coolcoding"]
      interval: 5s
      timeout: 5s
      retries: 5

  test-app:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      test-db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://testuser:testpass@test-db:5432/test_coolcoding
      TESTING: "true"
    volumes:
      - .:/app
    command: python -m pytest tests/ -v --tb=short --cov=app --cov-report=term-missing

volumes:
  test_db_data: