name: Code Quality Checks

on:
  pull_request:
    branches: [main]  # or whatever your default branch is

jobs:
  lint-and-type-check:
    name: Lint, Format, and Type Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Adjust as needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff black flake8 mypy

      - name: Run Black (check only)
        run: black --check .

      - name: Run Ruff
        run: ruff .

      - name: Run Flake8
        run: flake8 .

      - name: Run mypy
        run: mypy .
